language: node_js

node_js:
  - "4.7"
  - "6.9"

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

deploy:
  provider: npm
  email: "apiteam@swagger.io"
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
